server:
  port: 7001

#Eureka
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: true  #表示是否向Eureka注册中心注册自己
    fetch-registry: false #false表示自己为注册中心
    service-url:
      defaultZone: http://127.0.0.1:7002/eureka/